#Модуль Охраны
- type: Tag
  id: SecModul

- type: entity
  id: BaseModuleSec
  parent: BaseBorgModule
  abstract: true
  components:
  - type: Tag
    tags:
    - SecModul
  - type: BorgModule
    borgFitTypes:
    - borg-type-security
  - type: Sprite
    sprite: _Adventure/Roles/BorgDep/SecBorg/modul.rsi
  - type: Item
    storedRotation: -90
    inhandVisuals:
      left:
      - state: base-icon-inhand-left
        color: "#b86221"
      - state: base-module-inhand-left
        color: "#85282a"
      - state: base-part-inhand-left
      - state: base-stripes-inhand-left
        color: "#85282a"
      right:
      - state: base-icon-inhand-right
        color: "#b86221"
      - state: base-module-inhand-right
        color: "#85282a"
      - state: base-part-inhand-right
      - state: base-stripes-inhand-right
        color: "#85282a"

- type: entity
  id: ModuleSec
  parent: [ BaseModuleSec, BaseProviderBorgModule ]
  description: Всё для вас и вашей безопасности.
  name: охранный модуль киборга
  components:
  - type: BorgModuleIcon
    icon: { sprite: _Adventure/Roles/BorgDep/SecBorg/modul.rsi, state: Sec-module }
  - type: Sprite
    layers:
    - state: SecModul
    - state: SecModul-icon
  - type: ItemBorgModule
    hands:
    - item: FlashSecBorg
    - item: StunbatonSecBorg
    - item: WeaponLaserSecBorg

#Усмиритель
- type: entity
  name: Усмиритель MK-2
  noSpawn: false
  parent: BaseWeaponBatterySmall
  id: WeaponLaserSecBorg
  description: Для особо буйных.
  components:
  - type: Item
    sprite: _Adventure/Roles/BorgDep/SecBorg/Borg_laser_gun.rsi
  - type: Sprite
    sprite: _Adventure/Roles/BorgDep/SecBorg/Borg_laser_gun.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-unshaded-4
      map: ["enum.GunVisualLayers.MagUnshaded"]
      shader: unshaded
  - type: Gun
    selectedMode: SemiAuto
    fireRate: 3
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/taser2.ogg
  - type: BatteryAmmoProvider
    proto: BulletDisabler
    fireCost: 100
  - type: BatteryWeaponFireModes
    fireModes:
    - proto: BulletDisabler
      fireCost: 100
    - proto: BorgLethalBullet
      fireCost: 100
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 20
  - type: MagazineVisuals
    magState: mag
    steps: 5
    zeroVisible: false

- type: entity
  id: BorgLethalBullet
  noSpawn: true
  name: летальный заряд
  parent: BaseBullet
  components:
  - type: Projectile
    damage:
      types:
        Heat: 12
    ignoreWhitelist:
     tags:
     - Swarmer
  - type: Sprite
    sprite: _Adventure/Roles/BorgDep/SecBorg/Borg_laser_gun.rsi
    layers:
    - state: OmniLetal
      shader: unshaded
  - type: PointLight
    enabled: true
    color: "#ff4052"
    radius: 1.5
    energy: 2

#Дубинка-шокер киборга
- type: entity
  name: дубинка-шокер киборга
  parent: Stunbaton
  id: StunbatonSecBorg
  description: Электрошоковая дубинка для выведения людей из строя.
  noSpawn: false
  components:
  - type: BatterySelfRecharger
    autoRecharge: true
    autoRechargeRate: 10

#Вспышка киборга
- type: entity
  name: вспышка киборга
  parent: Flash
  id: FlashSecBorg
  description: Сверхяркая вспышка со спусковым механизмом.
  noSpawn: false
  components:
  - type: Sprite
    sprite: Objects/Weapons/Melee/flash.rsi
    layers:
    - state: burnt
      map: [ "enum.FlashVisualLayers.BaseLayer" ]
    - state: flashing
      map: [ "enum.FlashVisualLayers.LightLayer" ]
      visible: false
      shader: unshaded
  - type: LimitedCharges
    maxCharges: 10
    charges: 10
  - type: AutoRecharge
    rechargeDuration: 30
  - type: GenericVisualizer
    visuals:
      enum.FlashVisuals.Burnt:
        enum.FlashVisualLayers.BaseLayer:
          True: {state: burnt}
      enum.FlashVisuals.Flashing:
        enum.FlashVisualLayers.LightLayer:
          True: {visible: true}
          False: {visible: false}


