#Created: raidgo Transferred:  depresh
- type: entity
  name: гипоспрей ОБР
  suffix: Adventure
  parent: BaseHypospray
  description: Очень дорогой, рассчитанный на скорость гипоспрей. Производится на заводах дочерней компании Nanotrasen.
  id: HyposprayERT
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Objects/ERThypo.rsi
    state: hypo
  - type: Item
    sprite: _Adventure/Roles/SpecialForces/Objects/ERThypo.rsi
  - type: SolutionContainerManager
    solutions:
      hypospray:
        maxVol: 20
  - type: RefillableSolution
    solution: hypospray
  - type: ExaminableSolution
    solution: hypospray
  - type: UseDelay
    delay: 0
  - type: StaticPrice
    price: 70050
  - type: Tag
    tags:
    - HighRiskItem
  - type: StealTarget
    stealGroup: Hypospray
