#Created: raidgo Transferred:  depresh
- type: entity
  name: инъектор сильных нанитов
  parent: BaseHypospray
  description: Стерильный инъектор самых сильных нанитов. Это передовая разработка НТ, предназначенная только для самых элитных отрядов, таких как Эскадрон Смерти. Он способен вылечить практически все, однако не способен восстановить тело из отдельных органов. Также он сильно стимулирует организм, улучшая реакцию и обеспечивая огромные дозы адреналина в кровь, который, к удивлению, не наносит вреда.
  id: InjectorFullNanits
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
    state: combat_hypo
  - type: Item
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
  - type: SolutionContainerManager
    solutions:
      hypospray:
        reagents:
        - ReagentId: fullnanits
          Quantity: 100
        maxVol: 100
  - type: Injector
    allowedModes:
    - HyposprayInjectMode
  - type: UseDelay
    delay: 0.5
  - type: StaticPrice
    price: 0

- type: entity
  name: инъектор средних нанитов
  parent: BaseHypospray
  description: Стерильный инъектор нанитов. Это передовая разработка НТ, предназначенная для элитных отрядов, например, таких как ОБР или РХБЗЗ. Способен излечить многие недуги, однако не восстановит тело из органов. Также стимулирует организм, улучшая реакцию и обеспечивая адреналин в кровь.
  id: InjectorMediumNanits
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
    state: combat_hypo
  - type: Item
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
  - type: SolutionContainerManager
    solutions:
      hypospray:
        reagents:
        - ReagentId: Mediumnanits
          Quantity: 30
        maxVol: 30
  - type: Injector
    allowedModes:
    - HyposprayInjectMode
  - type: UseDelay
    delay: 0.5
  - type: StaticPrice
    price: 0

- type: entity
  name: инъектор слабых нанитов
  parent: BaseHypospray
  description: Стерильный инъектор нанитов. Это передовая разработка НТ, предназначенная для боевых отрядов, таких как ЦСС. Способен излечить многие недуги, однако не восстановит тело из органов. Также немного стимулирует организм, улучшая реакцию и обеспечивая небольшой приток адреналина в кровь.
  id: InjectorWeakNanits
  components:
  - type: Sprite
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
    state: combat_hypo
  - type: Item
    sprite: _Adventure/Roles/SpecialForces/Objects/nanit.rsi
  - type: SolutionContainerManager
    solutions:
      hypospray:
        reagents:
        - ReagentId: weaknanits
          Quantity: 30
        maxVol: 30
  - type: Injector
    allowedModes:
    - HyposprayInjectMode
  - type: UseDelay
    delay: 0.5
  - type: StaticPrice
    price: 0
