- type: entity
  name: Х-2 двухфазовый энергетический пистолет
  parent: BaseWeaponBatterySmall
  id: WeaponX2DualphaseEnergyLaserGun
  description: Этот передовой и дорогой лазерный пистолет офицера синий щит был изготовлен на заказ. Он сочетает в себе мощь и функциональность. Пистолет имеет два режима стрельбы - лазер, который наносит урон ожогами на расстоянии, и станнер, предназначенный для обезвреживания и задержания противников. Имеет слабую самозарядку.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/Weapons/DualphasBH.rsi
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-unshaded-4
      map: ["enum.GunVisualLayers.MagUnshaded"]
      shader: unshaded
  - type: Gun
    fireRate: 2
    projectileSpeed: 50
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/_Adventure/Weapon/BHWeapon.ogg
  - type: Item
    sprite: _Adventure/Roles/blueshield/Weapons/DualphasBH.rsi
    size: Small
  - type: BatteryAmmoProvider
    proto: LaserBulletForBH
    fireCost: 200
  - type: BatteryWeaponFireModes
    fireModes:
    - proto: LaserBulletForBH
      fireCost: 200
    - proto: stanerBullet
      fireCost: 100
  - type: Battery
    maxCharge: 2800
    startingCharge: 2800
  - type: MagazineVisuals
    magState: mag
    steps: 5
    zeroVisible: true
  - type: Appearance
  - type: StaticPrice
    price: 1000
  - type: BatterySelfRecharger
    autoRechargeRate: 40
    autoRecharge: true

# проджект лазера
- type: entity
  name: лазер
  id: LaserBulletForBH
  parent: EmitterBolt
  noSpawn: true
  components:
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/Weapons/UnivProjectiles.rsi
    layers:
    - state: omnilaser_greyscale
      shader: unshaded
      color: blue
  - type: Projectile
    impactEffect: BulletImpactEffectLaserForBH
    damage:
      types:
        Heat: 20

# проджект станнера
- type: entity
  name: станнер
  id: stanerBullet
  parent: BulletDisabler
  noSpawn: true
  components:
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/Weapons/UnivProjectiles.rsi
    layers:
    - state: omnilaser_greyscale
      shader: unshaded
      color: cyan
  - type: StaminaDamageOnCollide
    damage: 25
  - type: Projectile
    impactEffect: BulletImpactEffectDisablerBlue
    damage:
      types:
        Heat: 3
    soundHit:
      collection: WeakHit
    forceSound: true

# эффект от станнера
- type: entity
  id: BulletImpactEffectDisablerBlue
  noSpawn: true
  components:
    - type: TimedDespawn
      lifetime: 0.2
    - type: Sprite
      drawdepth: Effects
      layers:
        - shader: unshaded
          map: ["enum.EffectLayers.Unshaded"]
          sprite: _Adventure/Roles/blueshield/Weapons/UnivProjectiles.rsi
          state: impact_laser_greyscale
          color: cyan
    - type: EffectVisuals
    - type: Tag
      tags:
        - HideContextMenu

# эффект от лазера
- type: entity
  id: BulletImpactEffectLaserForBH
  noSpawn: true
  components:
    - type: TimedDespawn
      lifetime: 0.2
    - type: Sprite
      drawdepth: Effects
      layers:
        - shader: unshaded
          map: ["enum.EffectLayers.Unshaded"]
          sprite: _Adventure/Roles/blueshield/Weapons/UnivProjectiles.rsi
          state: impact_laser_greyscale
          color: blue
    - type: EffectVisuals
    - type: Tag
      tags:
        - HideContextMenu
