- type: entity
  name: офицерский клинок
  parent: [BaseSword, BaseRestrictedContraband]
  id: BlueshieldSabre
  suffix: Adventure
  description: Церемониальное оружие, принадлежащее офицеру синий щит.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/Weapons/Sable/Sable.rsi
  - type: MeleeWeapon
    attackRate: 1.5
    damage:
      types:
        Slash: 15 #cmon, it has to be at least BETTER than the rest.
    soundHit:
        path: /Audio/Weapons/bladeslice.ogg
  - type: Reflect
    reflectProb: .1
    spread: 90
  - type: Item
    sprite: _Adventure/Roles/blueshield/Weapons/Sable/Sable.rsi
  - type: DisarmMalus
  - type: Tag
    tags:
    - CaptainSabre
  - type: Contraband
    allowedDepartments: [ Command ]

- type: entity
  parent: [ClothingBeltBase, ClothingSlotBase, BaseRestrictedContraband]
  id: ClothingBeltSheathBS
  name: офицерские сабельные ножны
  suffix: Adventure
  description: Удобное хранилище для клинка офицера синий щит.
  components:
  - type: Sprite
    sprite: _Adventure/Roles/blueshield/Weapons/Sable/sheath.rsi
    state: sheath
  - type: Clothing
    sprite: _Adventure/Roles/blueshield/Weapons/Sable/sheath.rsi
  - type: Item
    size: Ginormous
  - type: ItemSlots
    slots:
      item:
        name: Sabre
        insertVerbText: sheath-insert-verb
        ejectVerbText: sheath-eject-verb
        insertSound: /Audio/Items/sheath.ogg
        ejectSound: /Audio/Items/unsheath.ogg
        whitelist:
          tags:
          - CaptainSabre
  - type: ItemMapper
    mapLayers:
      sheath-sabre:
        whitelist:
          tags:
          - CaptainSabre
  - type: Appearance
  - type: ContainerFill
    containers:
      item:
      - BlueshieldSabre
